# Generated by Django 4.0.4 on 2022-05-31 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(default=0)),
                ('puntaje', models.IntegerField(default=0)),
                ('nivel_1', models.CharField(default='', max_length=10)),
                ('nivel_2', models.CharField(default='', max_length=10)),
                ('nivel_3', models.CharField(default='', max_length=10)),
                ('nivel_4', models.CharField(default='', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
