# Generated by Django 4.0.4 on 2022-05-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='itemsIds',
            field=models.CharField(default='', max_length=10),
        ),
    ]
