# Generated by Django 4.0.4 on 2022-05-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0002_usuario_itemsids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
            ],
        ),
    ]
