# Generated by Django 4.0.4 on 2022-06-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0003_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='itemActivo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
