# Generated by Django 4.0.4 on 2022-06-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0004_usuario_itemactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='itemsIds',
            field=models.CharField(default='', max_length=20),
        ),
    ]
